---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: Para resolverla es necesario usar `if`
  checked: true
- value: Para resolverla es necesario usar `else` y/o `elif`
  checked: true
- value: "`a_romanos` debe tomar dos parámetros"
  checked: false
- value: Para resolverla conviene utilizar `str.startswith`
  checked: false
- value: El parámetro de `a_romanos` debe ser de tipo string
  checked: false
- value: El parámetro de `a_romanos` debe ser de tipo entero
  checked: true
- value: "`a_romanos` debe retornar un string"
  checked: true
- value: "`a_romanos` debe retornar un entero"
  checked: false
- value: Para resolverla conviene utilizar el operador de comparación `==`
  checked: true
name: Todos los números conducen a Roma
