---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: Para resolverla es necesario usar `if`
  checked: false
- value: Para resolverla es necesario usar `else` y/o `elif`
  checked: false
- value: "`es_pregunta` debe tomar dos parámetros"
  checked: false
- value: Para resolverla conviene utilizar `str.startswith`
  checked: false
- value: El parámetro de `es_pregunta` debe ser de tipo string
  checked: true
- value: El parámetro de `es_pregunta` debe ser de tipo entero
  checked: false
- value: "`es_pregunta` debe retornar un entero"
  checked: false
- value: "`es_pregunta` debe retornar un booleano"
  checked: true
- value: Para resolverla conviene utilizar el operador `not`
  checked: false
name: "¡Qué pregunta!"
